/**
 * One-time script to send Executive Summary emails
 * Run: node server/scripts/sendExecutiveSummary.js
 */

require('dotenv').config({ path: require('path').join(__dirname, '../.env') });
const sgMail = require('@sendgrid/mail');
const fs = require('fs');
const path = require('path');

sgMail.setApiKey(process.env.SENDGRID_API_KEY);

const FROM_EMAIL = 'james@silverfoxmedia.co';
const TO_EMAIL = 'james@silverfoxmedia.co';

// Read the markdown files
const v1Content = fs.readFileSync(
    path.join(__dirname, '../../investment-executive-summary.md'),
    'utf8'
);

const v2Content = fs.readFileSync(
    path.join(__dirname, '../../investment-executive-summary-v2.md'),
    'utf8'
);

// Convert markdown to simple HTML (basic conversion)
const mdToHtml = (md) => {
    return md
        // Headers
        .replace(/^### (.*$)/gm, '<h3 style="color:#333;margin-top:24px;">$1</h3>')
        .replace(/^## (.*$)/gm, '<h2 style="color:#017CFF;margin-top:32px;border-bottom:2px solid #017CFF;padding-bottom:8px;">$1</h2>')
        .replace(/^# (.*$)/gm, '<h1 style="color:#017CFF;font-size:28px;">$1</h1>')
        // Bold
        .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
        // Horizontal rules
        .replace(/^---$/gm, '<hr style="border:none;border-top:1px solid #ddd;margin:24px 0;">')
        // Tables (basic)
        .replace(/\|(.+)\|/g, (match) => {
            const cells = match.split('|').filter(c => c.trim());
            if (cells.some(c => c.includes('---'))) return '';
            const cellHtml = cells.map(c => `<td style="padding:8px;border:1px solid #ddd;">${c.trim()}</td>`).join('');
            return `<tr>${cellHtml}</tr>`;
        })
        // Lists
        .replace(/^- (.*$)/gm, '<li style="margin:4px 0;">$1</li>')
        .replace(/^(\d+)\. (.*$)/gm, '<li style="margin:4px 0;">$2</li>')
        // Paragraphs
        .replace(/\n\n/g, '</p><p style="line-height:1.6;color:#444;">')
        // Wrap in paragraph
        .replace(/^(.+)$/gm, (match) => {
            if (match.startsWith('<')) return match;
            return match;
        });
};

const htmlEmail = `
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body { font-family: 'Segoe UI', Arial, sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 20px; }
        h1 { color: #017CFF; }
        h2 { color: #017CFF; border-bottom: 2px solid #017CFF; padding-bottom: 8px; margin-top: 32px; }
        h3 { color: #333; margin-top: 24px; }
        table { border-collapse: collapse; width: 100%; margin: 16px 0; }
        th, td { padding: 10px; border: 1px solid #ddd; text-align: left; }
        th { background: #f5f5f5; }
        hr { border: none; border-top: 2px solid #017CFF; margin: 40px 0; }
        .version-header { background: #017CFF; color: white; padding: 16px; margin: 40px 0 20px; font-size: 20px; font-weight: bold; }
        pre { background: #f5f5f5; padding: 16px; overflow-x: auto; font-size: 13px; }
        ul, ol { padding-left: 24px; }
        li { margin: 6px 0; }
    </style>
</head>
<body>
    <p>James,</p>
    <p>Here are both versions of the MyMedicalCabinet Investment Executive Summary as requested.</p>

    <div class="version-header">VERSION 1: Investor Pitch Style</div>
    <div style="background:#fafafa;padding:20px;border:1px solid #ddd;">
        ${mdToHtml(v1Content)}
    </div>

    <div class="version-header">VERSION 2: Institutional Memo Style</div>
    <div style="background:#fafafa;padding:20px;border:1px solid #ddd;">
        ${mdToHtml(v2Content)}
    </div>

    <hr>
    <p style="color:#666;font-size:12px;">Generated by MyMedicalCabinet CTO Office<br>February 2, 2026</p>
</body>
</html>
`;

const msg = {
    to: TO_EMAIL,
    from: FROM_EMAIL,
    subject: 'MyMedicalCabinet - Investment Executive Summary (V1 & V2)',
    html: htmlEmail,
};

async function send() {
    try {
        await sgMail.send(msg);
        console.log('Email sent successfully to:', TO_EMAIL);
    } catch (error) {
        console.error('Error sending email:', error.response?.body || error.message);
        process.exit(1);
    }
}

send();
